# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: streaming.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstreaming.proto\x12\x06\x65vents\"5\n\tSubscribe\x12\x17\n\x0fsubscription_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x02 \x01(\t\"7\n\x0bUnsubscribe\x12\x17\n\x0fsubscription_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x02 \x01(\t\"$\n\tReconnect\x12\x17\n\x0fsubscription_id\x18\x01 \x01(\t\"\x81\x01\n\x0e\x43ontrolRequest\x12 \n\x03sub\x18\x01 \x01(\x0b\x32\x11.events.SubscribeH\x00\x12$\n\x05unsub\x18\x02 \x01(\x0b\x32\x13.events.UnsubscribeH\x00\x12 \n\x03rec\x18\x03 \x01(\x0b\x32\x11.events.ReconnectH\x00\x42\x05\n\x03req\"\xec\x02\n\x05\x45vent\x12\x0f\n\x07\x63ountry\x18\x01 \x01(\t\x12\x15\n\rsubscribed_by\x18\x02 \x03(\t\x12&\n\x07runtype\x18\x03 \x01(\x0e\x32\x15.events.Event.RunType\x12&\n\x07\x64\x65tails\x18\x04 \x01(\x0b\x32\x15.events.Event.Details\x1a\x64\n\x07\x44\x65tails\x12\x14\n\x0c\x64istance_kms\x18\x01 \x01(\x05\x12.\n\x0binclinetype\x18\x02 \x01(\x0e\x32\x19.events.Event.InclineType\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"5\n\x0bInclineType\x12\x07\n\x03NON\x10\x00\x12\x07\n\x03LOW\x10\x01\x12\n\n\x06MEDIUM\x10\x02\x12\x08\n\x04HIGH\x10\x03\"N\n\x07RunType\x12\x07\n\x03\x41NY\x10\x00\x12\n\n\x06STREET\x10\x01\x12\x11\n\rCROSS_COUNTRY\x10\x02\x12\r\n\tMOUNTAINS\x10\x03\x12\x0c\n\x08ON_TRACK\x10\x04\x32I\n\x0c\x45ventService\x12\x39\n\x0cStreamEvents\x12\x16.events.ControlRequest\x1a\r.events.Event(\x01\x30\x01\x42\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_SUBSCRIBE']._serialized_start=27
  _globals['_SUBSCRIBE']._serialized_end=80
  _globals['_UNSUBSCRIBE']._serialized_start=82
  _globals['_UNSUBSCRIBE']._serialized_end=137
  _globals['_RECONNECT']._serialized_start=139
  _globals['_RECONNECT']._serialized_end=175
  _globals['_CONTROLREQUEST']._serialized_start=178
  _globals['_CONTROLREQUEST']._serialized_end=307
  _globals['_EVENT']._serialized_start=310
  _globals['_EVENT']._serialized_end=674
  _globals['_EVENT_DETAILS']._serialized_start=439
  _globals['_EVENT_DETAILS']._serialized_end=539
  _globals['_EVENT_INCLINETYPE']._serialized_start=541
  _globals['_EVENT_INCLINETYPE']._serialized_end=594
  _globals['_EVENT_RUNTYPE']._serialized_start=596
  _globals['_EVENT_RUNTYPE']._serialized_end=674
  _globals['_EVENTSERVICE']._serialized_start=676
  _globals['_EVENTSERVICE']._serialized_end=749
# @@protoc_insertion_point(module_scope)
